merchex/merchex/urls.py
# ~/projects/django-web-app/merchex/merchex/urls.py

from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('bands/add/', views.band_create, name='band-create'),
    path('about-us/', views.about),
    path('contact-us/', views.contact, name='contact'),
]

merchex/listings/models.py
# listings/models.py

from django.db import models

# Create your models here.


# listings/models.py

from django.core.validators import MaxValueValidator, MinValueValidator
...


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)

    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):

    class ListingType(models.TextChoices):
        RECORDS = 'R'
        CLOTHING = 'C'
        POSTERS = 'P'
        MISC = 'M'

    # Nom de l'élément de la liste
    name = models.fields.CharField(max_length=100)
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    description = models.fields.CharField(max_length=1000)
    year = models.fields.IntegerField(
        null=True,
        validators=[MinValueValidator(1900),
                    MaxValueValidator(2021)]
    )
    sold = models.fields.BooleanField(default=False)

    # Ajout du champ ForeignKey pour lier à un Band
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

    class ListingType(models.TextChoices):
        RECORDS = 'R'
        CLOTHING = 'C'
        POSTERS = 'P'
        MISC = 'M'

    # Changement de title à name pour cohérence
    name = models.fields.CharField(max_length=100)
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    description = models.fields.CharField(max_length=1000)
    year = models.fields.IntegerField(
        null=True,
        validators=[MinValueValidator(1900),
                    MaxValueValidator(2021)]
    )
    sold = models.fields.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

merchex/listings/forms.py
# listings/forms.py

from django import forms
from listings.models import Band


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')  # ajoutez cette ligne

merchex/listings/views.py
# ~/projects/django-web-app/merchex/listings/views.py

from listings.models import Band
from django.http import HttpResponse
from django.shortcuts import render
from listings.forms import ContactUsForm
from django.core.mail import send_mail
from django.shortcuts import redirect  # ajoutez cet import
from listings.forms import BandForm, ContactUsForm


# listings/views.py


def hello(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html',
                  {'bands': bands})


def band_list(request):
    # Récupère tous les objets Band
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, id):
    # nous insérons cette ligne pour obtenir le Band avec cet id
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  # nous mettons à jour cette ligne pour passer le groupe au gabarit
                  {'band': band})


def about(request):
    return HttpResponse('<h1>À propos</h1> <p>Nous adorons merch !</p>')


def contact(request):
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {
                    form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
        return redirect('contact')  # ajoutez cette instruction de retour

    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).

    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()

    return render(request,
                  'listings/contact.html',
                  {'form': form})


# listings/views.py

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            return redirect('band-detail', band.id)
    else:
        # Si c'est une requête GET ou si le formulaire n'est pas valide
        form = BandForm()

    # Toujours retourner un HttpResponse
    return render(request, 'listings/band_create.html', {'form': form})


def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            # Correction: suppression de la parenthèse en trop
            return redirect('band-detail', band.id)
    else:
        # Si c'est une requête GET ou si le formulaire n'est pas valide
        form = BandForm(instance=band)

    # Toujours retourner un HttpResponse
    return render(request, 'listings/band_update.html', {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

        # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                  'listings/band_delete.html',
                  {'band': band})

merchex/listings/templates/listings/band_create.html
<h1>Créer un nouveau groupe</h1>

<form action="" method="post" >
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

merchex/listings/templates/listings/band_delete.html
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

merchex/listings/templates/listings/band_detail.html
<!-- # listings/templates/listings/band_detail.html -->

{% extends 'listings/base.html' %}

{% block content %}

{% for band in bands %}
     <li><a href="">{{ band.name }}</a></li>
   {% endfor %}

<ul>
<li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 {% if band.official_homepage %}
 <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
 {% endif %}
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
<!-- # listings/templates/listings/band_list.html -->

{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
 {% for band in bands %}
 <li>
    <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
    - <a href="{% url 'band-update' band.id %}">[modifier]</a>
    - <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
</li>
 {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
<h1>Mise à jour du groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>
    <body>

        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'contact' %}">Contact us</a>
          </nav>

        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
 {{ form.as_p }}
<input type="submit" value="Envoyer">
</form>